### ISSUE TITLE
操作步骤5

### ISSUE THREAD

**Issue by a08690025** [Janrilw/limbus-corporation-auto#4]
請問 5.用cd指令跳转到本仓库目录 要打什麼指令?

**Comment by Janrilw** [comment]
您可以使用cd命令在Windows的cmd应用中跳转到不同的目录或文件夹。[[1]](https://www.techwalla.com/articles/how-to-use-quotcdquot-command-in-command-prompt-window) [[2]](https://www.howtogeek.com/659411/how-to-change-directories-in-command-prompt-on-windows-10/) [[3]](https://www.minitool.com/news/how-to-change-directory-in-cmd.html)

例如，如果您想跳转到E盘的limbus-company-auto文件夹，您可以先输入E:切换到E盘，然后输入cd limbus-company-auto跳转到该文件夹。 [[2]](https://www.howtogeek.com/659411/how-to-change-directories-in-command-prompt-on-windows-10/) [[3]](https://www.minitool.com/news/how-to-change-directory-in-cmd.html)

如果您想返回上一级目录，您可以输入cd ..。
如果您想查看当前目录下的文件和文件夹，您可以输入dir。 [[2]](https://www.howtogeek.com/659411/how-to-change-directories-in-command-prompt-on-windows-10/) [[4]](https://www.digitalcitizen.life/command-prompt-how-use-basic-commands/)

**Comment by a08690025** [comment]
我對miniconda3資料夾 右鍵 在此處打開命令提示符 输入python limbus_corp.py 沒有limbus_corp.py這個檔案

**Comment by Janrilw** [comment]
可以尝试使用limbus_corp.py的完整路径代替之。

**Comment by a08690025** [comment]
我搜尋 limbus_corp.py 沒有這個檔案 還是我少安裝什麼?

**Comment by Janrilw** [comment]
你是不是没下载这个仓库？limbus_corp.py就在这个仓库里。
因为是熟练使用者所以不可避免地忽略了一些步骤。

**Comment by a08690025** [comment]
了解 謝謝

**Comment by a08690025** [comment]
重裝模組 發現
(base) D:\Users\P>conda install pyautogui
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyautogui

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by Janrilw** [comment]
conda装不了就把conda换成pip

**Comment by a08690025** [comment]
pip 裝成功了

**Comment by a08690025** [comment]
(base) C:\>CD C:\ProgramData\miniconda3

(base) C:\ProgramData\miniconda3>python limbus_corp.py
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\limbus_corp.py", line 22, in <module>
    from base import Game, Panel, Widget
  File "C:\ProgramData\miniconda3\base.py", line 17, in <module>
    from screenshot import window_capture
  File "C:\ProgramData\miniconda3\screenshot.py", line 101, in <module>
    from baseImage import Image as Image2
  File "C:\ProgramData\miniconda3\baseImage\__init__.py", line 2, in <module>
    from .base_image import Image
  File "C:\ProgramData\miniconda3\baseImage\base_image.py", line 6, in <module>
    from .coordinate import Rect, Size
  File "C:\ProgramData\miniconda3\baseImage\coordinate.py", line 9, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'

**Comment by Janrilw** [comment]
这个也是要再装一个pydantic

**Comment by a08690025** [comment]
pip install pydantic 裝完 目前 輸入python limbus_corp.py 會轉跳到遊戲 然後 手動操做完成一次镜之地牢嗎?

**Comment by Janrilw** [comment]
是的，需要游戏在1080p下以英文运行。
程序使用的是SIFT算法做的图像匹配，而月计没有给贴图上mipmap导致低分辨率下识别率很差，且对于变形的抗性很弱，实际使用还是会有低概率会卡死。
这个脚本因为事务繁忙已经无力维护，属于是勉强能用的程度。

**Comment by a08690025** [comment]
通關镜之地牢後 在输入python limbus_corp.py 就會自己打下一輪?

**Comment by Janrilw** [comment]
打完以后建议直接关闭这个脚本重新开，当时没有写多次重开的功能。

**Comment by a08690025** [comment]
了解 謝謝
